Step4
wdj4606/kotlin-lotto pull request #4
Opened 2023-12-07 15:01 UTC by creativeYS

2023-12-09 03:27 UTC, wdj4606 requested changes
챕장님! 구현 너무 잘해주셨습니다! 👍 
몇 가지 피드백 남겼으니 확인 부탁드립니다!

2023-12-09 03:27 UTC, wdj4606 commented on src/main/kotlin/lotto/view/InputView.kt
> +    fun inputManual(): List<List<Int>> {
해당 부분에서 List<Lotto>로 반환하는게 좋지 않을까요? 🤔 주어진 값을 통하여 로또 유효성 검사까지 같이 할 수 있을거 같습니다!

2023-12-09 03:27 UTC, wdj4606 commented on src/test/kotlin/lotto/utils/StatisticsUtilTest.kt
> +                    Lotto(1, 2, 3, 10, 11, 12), LottoNum(13)
만약 로또 넘버가 `1,2,3,10,11,12` 인데 보너스 넘버를 `12`를 넣는다고 한다면 어떻게 될까요? 🤔 
`WinLotto에 보너스 번호와 로또번호는 중복이 될수 없다` 라는 책임이 있는게 좋지 않을까요?

2023-12-10 06:09 UTC, creativeYS commented on src/test/kotlin/lotto/utils/StatisticsUtilTest.kt
> +                    Lotto(1, 2, 3, 10, 11, 12), LottoNum(13)
지당하십니다.

2023-12-10 06:09 UTC, creativeYS commented on src/main/kotlin/lotto/view/InputView.kt
> +    fun inputManual(): List<List<Int>> {
List<Lotto> 로 변환..!

2023-12-10 07:05 UTC, wdj4606 approved these changes
챕장님! 피드백 반영 너무 잘해주셨습니다! 👍 
역시 너무 잘하시네요 초반 단계에서 설계를 너무 잘해주셔서 지금까지 잘해주셨던거 같습니다 😄 머지할테니! 개인적인 리팩토링 하실건 자유롭게 해주시면 됩니다!
그동안 수고 많으셨습니다!

2023-12-10 07:05 UTC, wdj4606 commented on src/main/kotlin/lotto/domain/LottoWin.kt
> +class LottoWin(val lotto: Lotto, val bonus: LottoNum) {
크.. 아주 좋습니다! LottoWin이라는 클래스를 통하여 당첨번호에 대한 부분은 해당 클래스를 통해 알 수 있겠네요! 👍

2023-12-10 07:05 UTC, merged