<추가> (Step1) : 문자열 덧셈 계산기
wdj4606/kotlin-lotto pull request #5
Opened 2024-07-23 12:51 UTC by phj0319

덧셈 계산기 구현 및 테스트 코드 추가

2024-07-23 13:26 UTC, wdj4606 requested changes
홍진님 1단계 구현 잘해주셨습니다! 
좀 더 객체지향적으로 생각해서 설계해주시고, 각각의 객체들 간에 책임과 로직을 어떻게 구성할 수 있을지 생각해봐주시면 좋겠습니다! 
몇가지 피드백 남겼으니 확인부탁드려요!

2024-07-23 13:26 UTC, wdj4606 commented on src/main/kotlin/StringAddCalculator.kt
> +fun main () {
이번 단계에선 main으로 찍을 필요 없습니다!

2024-07-23 13:26 UTC, wdj4606 commented on src/main/kotlin/StringAddCalculator.kt
> +        }
지금 받은 text String값을 통해서 set과 로직이 뒤섞여 있는것 처럼 보입니다.
text에서 주어진 요구사항대로 Delimiter를 분리한 뒤, 분리한 값을 더하는 로직만 필요한게 아닐까요?

2024-07-23 13:26 UTC, wdj4606 commented on src/main/kotlin/StringAddCalculator.kt
> +        check(positive >= 0) { throw NumberFormatException(MSG_EXCEPTION_NEGATIVE) }
`check()` 함수는 기본적으로 IllegealStateException를 던지는 형태로 구성되어있습니다. 
만약 다른 Exception을 던지고 싶으시면, if문으로 열어서 던져주셔야 합니다.

2024-07-23 13:26 UTC, wdj4606 commented on src/main/kotlin/StringAddCalculator.kt
> +        return Pair(delimiter, remainingText)
이 함수에서 Delimiter도 판단하고, text도 쪼개서 보내는게 좋지 않을까요?

2024-07-23 13:26 UTC, wdj4606 commented on src/main/kotlin/StringAddCalculator.kt
> +        if (text.isBlank()) return 0
Empty()비교를 하셨으면, isBlank()는 안해주셔도 됩니다.` isEmpty()`와 `isBlank()`가 하는 로직은 동일해서요 ㅎㅎ

2024-07-23 16:01 UTC, phj0319 commented on src/main/kotlin/StringAddCalculator.kt
> +fun main () {
넵 정리하겠습니다

2024-07-23 16:01 UTC, phj0319 commented on src/main/kotlin/StringAddCalculator.kt
> +        }
넵 요부분 정리하겠습니다

2024-07-23 16:01 UTC, phj0319 commented on src/main/kotlin/StringAddCalculator.kt
> +        check(positive >= 0) { throw NumberFormatException(MSG_EXCEPTION_NEGATIVE) }
아하 넵. 혼동했네요 감사합니다!

2024-07-23 16:02 UTC, phj0319 commented on src/main/kotlin/StringAddCalculator.kt
> +        return Pair(delimiter, remainingText)
요부분은 다시 개발할 예정이라 갈아엎겠습니당

2024-07-23 16:02 UTC, phj0319 commented on src/main/kotlin/StringAddCalculator.kt
> +        if (text.isBlank()) return 0
앗 그렇군요! 중복 제거하겠습니다!

2024-07-23 16:04 UTC, phj0319 commented
샘플코드만 보고 하다가 너무 이상하게 했네요...
클래스 하나로 하던것을 클래스 세개로 나눠봤습니다!

1. 구분자 관리자
2. Splitter
3. 유효성 검증

2024-07-23 23:27 UTC, wdj4606 approved these changes
홍진님 피드백 반영 잘해주셨습니다 ㅎ
머지할테니 다음단계 진행해주세요!

2024-07-23 23:27 UTC, wdj4606 commented on src/test/kotlin/StringSplitterTest.kt
> +class StringSplitterText {
Text?? 오타가 난거 같네요! ㅎㅎ

2024-07-23 23:27 UTC, wdj4606 commented on src/test/kotlin/StringValidatorTest.kt
> +    @DisplayName(value = "빈 문자열 또는 null 값을 입력할 경우 0을 반환해야 한다.")
0을 반환해야한다가 아니고, 빈 문자열인지에 대한 여부를 반환하는게 아닐까요?

2024-07-23 23:27 UTC, merged

2024-07-24 03:15 UTC, phj0319 commented on src/test/kotlin/StringSplitterTest.kt
> +class StringSplitterText {
아이구 이런 이름 바꾸다가 그리되었군용;; 고치겠슴당

2024-07-24 04:08 UTC, phj0319 commented on src/test/kotlin/StringValidatorTest.kt
> +    @DisplayName(value = "빈 문자열 또는 null 값을 입력할 경우 0을 반환해야 한다.")
앗 문구 수정하겠습니다!