<step1> 문자열 계산기
wdj4606/kotlin-lotto pull request #6
Opened 2024-07-23 14:36 UTC by pcs0807

감사합니다.

2024-07-23 23:34 UTC, wdj4606 requested changes
찬석님! 1단계 구현 잘해주셨습니다! 
좀더 객체지향적으로 구조를 변경해보는건 어떨까요??
로직을 잘 분리해주셨지만, 로또를 진행하는데에 있어서 OOP적인 관점으로 구조를 잡아보는 연습을 해보셨으면 좋겠습니다! 😄

2024-07-23 23:34 UTC, wdj4606 commented on src/main/kotlin/Calculator/StringAddCalculator.kt
> +    }
분리하는 연산자를 찾아서 Pair로 반환할 이유가 있을까요? 계산하는 로직에서 split을 할때, 찾아서 같이 분리해주면 어떨까요??

2024-07-23 23:34 UTC, wdj4606 commented on src/main/kotlin/Calculator/StringAddCalculator.kt
> +        require(number != null) { NOT_NUMBER }
위에서 text.isNullOrBlank()로 해당 text가 null이 아닌지, 빈값이 아닌지를 판단했기 때문에, 이 로직에서 null이 아닐 경우가 있을까요?

2024-07-23 23:34 UTC, wdj4606 commented on src/main/kotlin/Calculator/StringAddCalculator.kt
> +    }
마찬가지로 해당 delimiter를 추가로 생성 하는게 아닌, 한번에 조합하여 split할수 있는 방법이 있지 않을까요?

2024-07-24 12:33 UTC, pcs0807 commented on src/main/kotlin/Calculator/StringAddCalculator.kt
> +        require(number != null) { NOT_NUMBER }
위에서 null을 반환하는 경우는 문자가 숫자가 아니라 알파벳같은 문자일 때 라고 생각해서 추가헀습니다.

2024-07-25 03:27 UTC, wdj4606 approved these changes
찬석님! 피드백 반영 잘해주셨습니다 
머지할테니 다음단계 진행해주세요!

2024-07-25 03:27 UTC, wdj4606 commented on src/main/kotlin/Calculator/DelimiterManager.kt
> +        val result = Regex("//(.*)\n(.*)").find(text)
문자열 포장해주세요!

2024-07-25 03:27 UTC, wdj4606 commented on src/main/kotlin/Calculator/StringAddCalculator.kt
> +fun main() {
1단계에선 main함수는 없어도 됩니다!

2024-07-25 03:27 UTC, wdj4606 commented on src/main/kotlin/Calculator/StringAddCalculator.kt
> +    private val tokenValidator = TokenValidator()
이렇게 초기화 할꺼면 기본 생성자로 기본인자 주는건 어떨까요?
```kotlin
class StringAddCalculator(private val delimiterManager = DelimiterManager(), 
                                          private val tokenValidator = TokenValidator()
)
```

2024-07-25 03:27 UTC, merged