Step2
wdj4606/kotlin-lotto pull request #7
Opened 2024-07-24 15:59 UTC by phj0319

2024-07-25 03:48 UTC, wdj4606 requested changes
홍진님! 2단계 구현 잘해주셨습니다 👍 
몇가지 피드백 남겼으니 확인부탁드립니다!

2024-07-25 03:48 UTC, wdj4606 commented on src/main/kotlin/lotto/LottoEventMachine.kt
> +    private val REWARD_VALUES = listOf(REWARD_1ST, REWARD_2ND, REWARD_3RD, REWARD_4TH, REWARD_5TH)
해당 로또 상금과 매칭 갯수를 enum으로 관리해보는건 어떨까요?

2024-07-25 03:48 UTC, wdj4606 commented on src/main/kotlin/lotto/LottoEventMachine.kt
> +            val rank = matchCount2Rank(count)
마찬가지로 이런 등수 매기는 것도 enum으로 관리를 해보는건 어떨까요?

2024-07-25 03:48 UTC, wdj4606 commented on src/main/kotlin/lotto/LottoEventMachine.kt
> +        return results
일반적으로 실생활에서의 로또의 모습으로 보았을땐, 로또 기계가 로또 번호를 발급하는 개념은 맞지만, 객체세계에선 어떨까요? 로또 번호와 당첨 번호라는 객체가 있을거고, 로또 번호에서 당첨 번호를 비교하여 등수가 얼마인지 알수 있는 책임이 맞지 않을까요?? 결국엔 로또 객체에서 당첨번호와 비교하여 현재 로또 객체가 등수가 몇등인지 아는게 맞지 않을까 생각이 듭니다.

2024-07-25 03:48 UTC, wdj4606 commented on src/main/kotlin/lotto/LottoEventMachine.kt
> +    }
마찬가지로 나온 결과를 가지고 출력하기 위해 총상금은 계산하는 로직으로 보이는데,
이 로직이 도메인 로직에 있는게 맞을까요?
단순히 출력에 필요한 계산이 발생하는 로직처럼 보입니다

2024-07-25 03:48 UTC, wdj4606 commented on src/main/kotlin/lotto/LottoEventMachine.kt
> +    }
이 count하는 로직을 적절히 맞는 클래스에 위임해야 할것으로 보입니다.

2024-07-25 03:48 UTC, wdj4606 commented on src/test/kotlin/LottoEventMachineTest.kt
> +        val results2 = LottoEventMachine.result(listOf(37,38,39,40,41,42), tickets)
lint가 적용이 안된거 같습니다. hook 설정 해주시고, ktLinkCheck한번 확인해주세요!

2024-07-25 03:48 UTC, wdj4606 commented on src/test/kotlin/LottoNumberGeneratorTest.kt
> +    }
과연 이 책임이 LottoNumberGenerator가 가지고 있는게 맞을까요??
만약 45이상에 숫자가 있을 경우엔 논리적인 오류를 어느 객체가 책임을 져야할까요?
아주 작은 단위의 객체부터 생각해보시면, 어느 부분에 책임이 있어야 하는지 알 수 있으실겁니다!

2024-07-25 03:48 UTC, wdj4606 commented on src/test/kotlin/LottoTicketTest.kt
> +    }
마찬가지로 로또 티켓이 6개의 숫자를 가지고 있는 상황에서 6개 숫자 모두가 1-45 사이의 정수만 존재해야한다라는 책임을 좀 더 작은 단위로 생각해보는건 어떨까요?
로또 번호는 1-45 사이의 정수값이다. 이런식으로요!

2024-07-25 03:48 UTC, wdj4606 commented on src/main/kotlin/lotto/LottoTicket.kt
> +class LottoTicket(private val generatorParam: GeneratorInterface = LottoNumberGenerator, val numbers: List<Int> = List(6) {generatorParam.generate()}.sorted())
로또 티켓이 로또 발급하는 부분을 알 필요가 있을까요? 
로또 티켓은 6개로 구성된 로또 번호만 알고 있으면 되지 않을까요?

2024-07-25 03:48 UTC, wdj4606 commented on src/test/kotlin/LottoTicketTest.kt
> +    }
로또 티켓은 6개의 숫자 List만 가진다 라는 책임은 명확한거 같습니다!
만약 6개 미만이나 7개 이상 가지게 될 경우에 에러가 발생하는 로직까지 책임을 만들어주시면 좋을거 같습니다!

2024-07-25 03:55 UTC, wdj4606 requested changes

2024-07-25 03:55 UTC, wdj4606 commented on src/main/kotlin/lotto/LottoNumberGenerator.kt
> +        return range.random()
random()함수로 뽑아내는 형태는 현재 로또 번호가 중복될 가능성이 보입니다.
shuffled()를 이용하여 섞은 뒤, 6개만 뽑아내는 형태가 맞지 않을까요?

```kotlin
range.shuffled()
.take(LOTTO_NUMBER_SIZE)
```

2024-07-29 04:27 UTC, phj0319 commented on src/main/kotlin/lotto/LottoEventMachine.kt
> +    private val REWARD_VALUES = listOf(REWARD_1ST, REWARD_2ND, REWARD_3RD, REWARD_4TH, REWARD_5TH)
넵 enum class로 묶어서 처리했습니다!

2024-07-29 04:27 UTC, phj0319 commented on src/main/kotlin/lotto/LottoEventMachine.kt
> +            val rank = matchCount2Rank(count)
넵 enum class로 묶어서 처리했습니다!

2024-07-29 04:57 UTC, phj0319 commented on src/main/kotlin/lotto/LottoEventMachine.kt
> +        return results
이 역할은 LottoTicket이 하도록 위임하였습니다.

2024-07-29 04:57 UTC, phj0319 commented on src/main/kotlin/lotto/LottoEventMachine.kt
> +    }
이 역할은 ResultView가 하도록 위임하였습니다.

2024-07-29 04:58 UTC, phj0319 commented on src/main/kotlin/lotto/LottoEventMachine.kt
> +    }
이 역할은 LottoTicket이 하도록 위임하였습니다.

2024-07-29 14:40 UTC, phj0319 commented on src/main/kotlin/lotto/LottoNumberGenerator.kt
> +        return range.random()
앗.. 그러네요 셔플드로 고쳤습니다!

2024-07-29 14:41 UTC, phj0319 commented on src/main/kotlin/lotto/LottoTicket.kt
> +class LottoTicket(private val generatorParam: GeneratorInterface = LottoNumberGenerator, val numbers: List<Int> = List(6) {generatorParam.generate()}.sorted())
음 넵 로또는 딱 번호만 전달받는것으로 바꿔보겠습니다

2024-07-29 14:48 UTC, phj0319 commented on src/test/kotlin/LottoNumberGeneratorTest.kt
> +    }
요 댓글과 바로 아래 댓글은 어떤 의도이신지 잘 이해가 되지 않네요...
내일 다시 문의드리겠습니다..!

2024-07-29 14:49 UTC, phj0319 commented on src/test/kotlin/LottoTicketTest.kt
> +    }
넵 추가 반영해보겠습니다!

2024-07-29 14:51 UTC, phj0319 commented on src/test/kotlin/LottoTicketTest.kt
> +    }
앗 그러고보니 바로 위에 lottoNumberSize 라는 함수가 있는데, 요거와는 다른것을 말씀하신 걸까요?

2024-07-29 23:33 UTC, wdj4606 approved these changes
홍진님 피드백 반영 잘해주셨습니다! 
머지할테니 다음 단계 진행해주세요!

2024-07-29 23:33 UTC, wdj4606 commented on src/main/kotlin/lotto/LottoTicket.kt
> +            }
getByRank라는 함수가 필요할까요?? 이미 enum값으로 몇등인지를 알수 있을거 같습니다!

2024-07-29 23:33 UTC, wdj4606 commented on src/main/kotlin/lotto/LottoTicket.kt
> +                else -> Fifth
해당 부분을 when을 사용하는거 보단 find를 사용하면 OCP를 위반하지 않는 형태로 만들수 있을거 같습니다!
```kotlin
return values().find { it.match == match } ?: Fifth
```

2024-07-29 23:33 UTC, wdj4606 commented on src/main/kotlin/lotto/LottoTicket.kt
> +    Fifth(5, 0, 2);
Enum 값 네이밍 규칙은 모두 대문자입니다!

2024-07-29 23:33 UTC, merged

2024-07-29 23:54 UTC, phj0319 commented on src/main/kotlin/lotto/LottoTicket.kt
> +            }
앗 그러네요ㅎㅎ

2024-07-29 23:55 UTC, phj0319 commented on src/main/kotlin/lotto/LottoTicket.kt
> +    Fifth(5, 0, 2);
넵 알겠습니다

2024-07-30 05:07 UTC, creativeYS commented
억ㅋㅋㅋㅋ 디테일한게 ㄷㄷㄷ